from .events import Event
from .user import CustomeUser
from .student import Student
from .staff import Staff
from .course import Course
from .session import Session
from .login import Login
from .subject import Subject
from .attandance import Student_Attendance
from .attandance_report import Student_Attendance_Report
from .attandance import Staff_Attendance
from .result import Result
from .notification import Staff_notification
from .admission import Admission
from .leave import *
from .contact_us import Contact_Us
from .gallery import Gallery
from .fees_receipt import Student_fees_Receipt
from .salary_receipt import Staff_salary_Receipt
from .student_note import Student_Note